### PR TITLE
Interface inheritance

### PR DESCRIPTION
**Pull request by MikeVeerman**
#18 Interface inheritance

Types can now inherit from interfaces. I've included minimal update to the docs since this is an edge case and I feel a complete chapter on "Interface Inheritance" would be a bit much.

### CODE REVIEW

**Comment by nicolasdao** [comment]
Fantastic @MikeVeerman. 

I'm in holidays ATM and I'm back on the 8th in Sydney. I'll do my best to review that before. Worst case scenario, I'll review it on the 8th. 

Thanks a lot for your work. 

Cheers,

Nic

**Comment by MikeVeerman** [comment]
Is there still something you expect me to do for this PR?

**Comment by Calcyfer** [comment]
@MikeVeerman There are a few files with conflicts that will need to be resolved first. :) Looks like it's mainly the order of the tests.

**Comment by nicolasdao** [comment]
Hi @MikeVeerman,

My sincere apologies for taking so long to review and test your PR. After fixing the conflicts and reviewing it, I'm happy to say that I've successfully merged into master. 

Thank you so much for submitting that one and sticking to our conventions and rules.

I hope I can see more PR in the futures.

@Calcyfer thanks for jumping into it.

Cheers everyone.

Nic

**Pull request merged**
