### PR TITLE
Add support for generic types in parameters

### PR DESCRIPTION
**Pull request by Calcyfer**
This PR will add support for generic types in type parameters.
I've added the relevant test and modified the readme to reflect the new feature.

### CODE REVIEW

**Comment by nicolasdao** [comment]
Fantastic @Calcyfer . 

I'm in holidays ATM and I'm back on the 8th in Sydney. I'll do my best to review that before. Worst case scenario, I'll review it on the 8th. 

Thanks a lot for your work. 

Cheers,

Nic

**Comment by iamdanthedev** [comment]
Hello guys
Any luck with this PR?
Seems to be a killer feature
Thanks

**Comment by Calcyfer** [comment]
@iamdanthedev Not yet, as the maintainer hasn't had time to check them yet, but I'm using a combination of the 2 currently open PRs in a project right now. 

Feel free to fork [that branch](https://github.com/Calcyfer/graphql-s2s/tree/aiv).

**Comment by iamdanthedev** [comment]
@Calcyfer thanks for the link!

**Comment by nicolasdao** [comment]
Great work @Calcyfer.

I've just reviewed your PR and everything was fine. I've merged it and released a new version on npm (0.17.0). I'm looking for collaborators, so if you're interested, let me know so I can add you as a contributor to this project.

Thanks again.

Nic

**Comment by Calcyfer** [comment]
Thanks @nicolasdao.

I'd be happy to contribute, so feel free to add me and I'll track the project and update when and where I can.

**Pull request merged**
